openapi: 3.0.0
info:
  version: 1.0.0
  title: Back End Demonstration API
  description: A simple Dog API
  contact:
    name: lau hok lung
    email: 217011770@stu.vtc.edu.hk
  license: 
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'https://DogAPI.hllaucode.repl.co/'
    description: Development Server
tags:
  - name: Users
    description: API endpoints for user management
  - name: Dogs
    description: Access and perform CRUD operations on dog entries.

paths:
  /dogs:
    post:
      tags:
        - Dogs
      description:
        Create a new dog.
      requestBody:
        description: All new dog data.
        required: true
        content:
          application/json:
            schema:
              $ref: ./dogs.json#/definitions/dogs
      responses:
        '201':
          description: Dogs created
  /dogs/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: Numeric id of the dog
    get:
      tags:
        - Dogs
      description:
        Get dog by id.
      responses:
        '200':
          description: View of an dog record
        '404':
          description: Dog was not found in the DB
    put:
      tags:
        - Dogs
      description:
        Update dog by ID.
      responses:
        '200':
          description: Update confirmation and link to record.
        '404':
          description: Dog was not found in the DB.
    delete:
      tags:
        - Dogs
      description:
        Delete dog by ID.
      responses:
        '200':
          description: Delete confirmation.
        '404':
          description: Dog was not found in the DB.
